### PR TITLE
Properly apply leave-to-class

### PR DESCRIPTION
**Pull request by NoahCardoza**
After a little digging the fix to that warning I found in #2 is pretty simple. Still stumped about the whole slots warning though...

### CODE REVIEW

**Comment by restyler** [comment]
I get the same warning messages in chrome console. Can we merge this in main? Thanks!

**Comment by alexis-riot** [comment]
I up this PR that can be really usefull. Thanks.

**Comment by dexcell** [comment]
Please merge

**Comment by emmanuelsw** [comment]
You can get rid of the slots warning (Non-function value encountered for default slot) by replacing this:
```js
// VTNotification.vue
[
  this.$slots.default({
    notifications: this.sortedNotifications,
    close: this.close,
  }),
]
```
with this:
```js
{
  default: () => {
    return this.$slots.default({
      notifications: this.sortedNotifications,
      close: this.close,
    })
  }
}
```

**Comment by killmenot** [comment]
Sorry guys, missed this PR

**Pull request merged**
